### ISSUE TITLE
[REQ] macOS Support

### ISSUE THREAD

**Issue by fakerybakery** [PocketInc/Pocket-Browser#3]
**General Information**:
```
Operating System: MacOS
Browser Version: 1.6.1
Error Code: (if found)
```

**Describe the bug**:
I built Pocket Browser for macOS, I typed `npm start`. 
Terminal log:
```fakerybakery@fakerybakery Pocket-Browser-1.6.1 % npm start

> pocket-browser@1.6.1 start
> electron .

(electron) Security Warning: A WebContents was just created with both webviewTag and contextIsolation enabled.  This combination is fundamentally less secure and effectively bypasses the protections of contextIsolation.  We strongly recommend you move away from webviews to OOPIF or BrowserView in order for your app to be more secure
```

A lot of 404 errors.

![screenshot_vkDJ6CWF_on_12-10-36-PM_2021-06-05@2x](https://user-images.githubusercontent.com/76186054/120902792-331c0380-c5f7-11eb-9fd0-25305540950a.png)

**Expected behavior**:
I expected it to just work so I could open new tabs and everything.

**Steps**:
1. Download Pocket Browser
2. cd to Pocket Browser on macOS
3. Run `npm start`
4. Try to open a new tab or something
 
**Log:**
I cannot access the log file because the browser won't load.

**Comment by AhmadHrb** [comment]
Hello @fakerybakery!

Thank you for your feedback and your interest in supporting the development.

Unfortunately, the browser doesn't currently support **macOS**. but due to the big amount of people asking for mac support on our support platforms, we will start building mac versions in the soon future.

We're currently working on a new update, and hopefully, if we manage to succeed in making the mac version function, it will be published on the [releases](https://github.com/PocketInc/Pocket-Browser/releases) page as well as our [website](https://pocket-inc.ml/browser).

Best Regards,
AhmadHrb.
**Pocket Team.**

**Comment by AhmadHrb** [comment]
As Mac Support is planned, the issue will stay opened till mac support arrive.
